// File generated by FlutterFire CLI.
// Run `dart pub global activate flutterfire_cli` then `flutterfire configure`
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform. '
          'Run: flutterfire configure',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsowkrxxGqcLvvF4lVpSotLslAM516Odc',
    appId: '1:895510156606:web:eae0055d29eca4c306886f',
    messagingSenderId: '895510156606',
    projectId: 'fir-test-37f31',
    authDomain: 'fir-test-37f31.firebaseapp.com',
    databaseURL: 'https://fir-test-37f31-default-rtdb.firebaseio.com',
    storageBucket: 'fir-test-37f31.firebasestorage.app',
    measurementId: 'G-T05H91VDRZ',
  );

  // Replace these with output from `flutterfire configure`

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAERsSoPvTu9z2Zm8kndQPqQYzLr_Tkc9M',
    appId: '1:895510156606:android:fe90edd33f6473ab06886f',
    messagingSenderId: '895510156606',
    projectId: 'fir-test-37f31',
    databaseURL: 'https://fir-test-37f31-default-rtdb.firebaseio.com',
    storageBucket: 'fir-test-37f31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyConCcmi7kF9iJgkey5TXOfC0WwIwPvHWE',
    appId: '1:895510156606:ios:1d0cc70d0ba06d8f06886f',
    messagingSenderId: '895510156606',
    projectId: 'fir-test-37f31',
    databaseURL: 'https://fir-test-37f31-default-rtdb.firebaseio.com',
    storageBucket: 'fir-test-37f31.firebasestorage.app',
    iosBundleId: 'com.taxifleet.taxiFleetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyConCcmi7kF9iJgkey5TXOfC0WwIwPvHWE',
    appId: '1:895510156606:ios:1d0cc70d0ba06d8f06886f',
    messagingSenderId: '895510156606',
    projectId: 'fir-test-37f31',
    databaseURL: 'https://fir-test-37f31-default-rtdb.firebaseio.com',
    storageBucket: 'fir-test-37f31.firebasestorage.app',
    iosBundleId: 'com.taxifleet.taxiFleetApp',
  );

  static bool get isConfigured => !web.apiKey.startsWith('YOUR_');
}